linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - typecheck
    - unused

run:
  timeout: 5m
  tests: true
  build-tags:
    - test

issues:
  max-issues-per-linter: 50

